### ISSUE TITLE
please change to relative path

### ISSUE THREAD

**Issue by mattvenn** [meriac/tt02-play-tune#1]
https://github.com/meriac/tt02-play-tune/blob/1c38f03f3a2763f813207f19f9b8ae48a2db120d/info.yaml#L29

**Comment by meriac** [comment]
Fixed with commit  https://github.com/meriac/tt02-play-tune/commit/27118b202ca74e5040227993b648192329e0dee7:
https://github.com/meriac/tt02-play-tune/blob/27118b202ca74e5040227993b648192329e0dee7/info.yaml#L29
